version: '2.1'  
volumes:  
  fin:
services:  
    blues-note:
      build: ./blues-note
      devices:
        - "/dev/i2c-1:/dev/i2c-1"
      ports:
        - "8765:8765"
        - "1337:1337"
      privileged: true

    finabler:
      restart: always
      image: balenablocks/finabler:latest
      network_mode: host
      privileged: true
      volumes:
        - 'fin:/data/firmware'
      labels:
        io.balena.features.supervisor-api: '1'
        io.balena.features.balena-api: '1'
      expose:
        - "1337"
